# Generated by Django 5.2.12 on 2026-03-12 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_address_alter_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aldeia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Aldeia')),
            ],
            options={
                'verbose_name': 'Aldeia',
                'verbose_name_plural': 'Aldeias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Additional Address / Notes'),
        ),
        migrations.AddField(
            model_name='patient',
            name='aldeia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patients.aldeia', verbose_name='Aldeia'),
        ),
        migrations.AddField(
            model_name='patient',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patients.municipio', verbose_name='Municipio'),
        ),
        migrations.CreateModel(
            name='PostoAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Posto Administrativo')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postos', to='patients.municipio')),
            ],
            options={
                'verbose_name': 'Posto Administrativo',
                'verbose_name_plural': 'Postos Administrativos',
                'ordering': ['name'],
                'unique_together': {('municipio', 'name')},
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='posto_administrativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patients.postoadministrativo', verbose_name='Posto Administrativo'),
        ),
        migrations.CreateModel(
            name='Suco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Suco')),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucos', to='patients.postoadministrativo')),
            ],
            options={
                'verbose_name': 'Suco',
                'verbose_name_plural': 'Sucos',
                'ordering': ['name'],
                'unique_together': {('posto', 'name')},
            },
        ),
        migrations.AddField(
            model_name='aldeia',
            name='suco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aldeias', to='patients.suco'),
        ),
        migrations.AddField(
            model_name='patient',
            name='suco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patients.suco', verbose_name='Suco'),
        ),
        migrations.AlterUniqueTogether(
            name='aldeia',
            unique_together={('suco', 'name')},
        ),
    ]
