# Generated by Django 5.2.12 on 2026-03-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_aldeia_municipio_alter_patient_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyqueue',
            options={'verbose_name': 'Daily Queue', 'verbose_name_plural': 'Daily Queues'},
        ),
        migrations.AddField(
            model_name='patient',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Registration Fee (USD)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Emergency Contact Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Emergency Contact Phone'),
        ),
    ]
