# Generated by Django 5.2.12 on 2026-03-23 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_dailyqueue_options_patient_registration_fee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': [('can_print_card', 'Can print patient ID card'), ('can_export_patients', 'Can export patient data'), ('view_menu_patients', 'Can see Patients menu in sidebar')], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterField(
            model_name='aldeia',
            name='suco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aldeias', to='patients.suco'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='aldeia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='patients.aldeia', verbose_name='Aldeia'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='patients.municipio', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='posto_administrativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='patients.postoadministrativo', verbose_name='Posto Administrativo'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='suco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='patients.suco', verbose_name='Suco'),
        ),
        migrations.AlterField(
            model_name='postoadministrativo',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postos', to='patients.municipio'),
        ),
        migrations.AlterField(
            model_name='suco',
            name='posto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucos', to='patients.postoadministrativo'),
        ),
    ]
