# Generated by Django 5.2.12 on 2026-03-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_options_alter_aldeia_suco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Full Name'),
        ),
    ]
