# Generated by Django 5.2.12 on 2026-03-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patient_full_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['full_name'], name='idx_patient_fullname'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone_number'], name='idx_patient_phone'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['-created_at'], name='idx_patient_created'),
        ),
    ]
