# Generated by Django 5.2.12 on 2026-04-07 23:47

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patient_idx_patient_fullname_and_more'),
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.AddIndex(
            model_name='patient',
            index=django.contrib.postgres.indexes.GinIndex(fields=['full_name'], name='idx_patient_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=django.contrib.postgres.indexes.GinIndex(fields=['phone_number'], name='idx_patient_phone_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
