# Generated by Django 5.2.12 on 2026-04-11 03:40

import clinic_core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patient_idx_patient_name_trgm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=clinic_core.fields.EncryptedTextField(blank=True, default='', verbose_name='Additional Address / Notes'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_phone',
            field=clinic_core.fields.EncryptedTextField(blank=True, max_length=255, null=True, verbose_name='Emergency Contact Phone'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=clinic_core.fields.EncryptedTextField(blank=True, max_length=255, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Kontribusi (USD)'),
        ),
    ]
