# Generated by Django 5.2.12 on 2026-04-11 05:14

import clinic_core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_patient_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Father Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mother Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_category',
            field=models.CharField(choices=[('RAI_LARAN', 'RAI LARAN (Local)'), ('RAI_LIUR', 'RAI LIUR (International)')], default='RAI_LARAN', max_length=10, verbose_name='Patient Category'),
        ),
        migrations.CreateModel(
            name='PatientID',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_type', models.CharField(choices=[('KTP', 'KTP (National ID)'), ('BI', 'BI (Bilhete de Identidade)'), ('PASSPORT', 'Passport'), ('ELECTORAL', 'Electoral Card'), ('OTHER', 'Other')], max_length=20, verbose_name='ID Type')),
                ('id_number', clinic_core.fields.EncryptedTextField(verbose_name='ID Number')),
                ('id_search_hash', models.CharField(db_index=True, max_length=64, verbose_name='Search Hash')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient Identification',
                'verbose_name_plural': 'Patient Identifications',
                'unique_together': {('id_type', 'id_search_hash')},
            },
        ),
    ]
