# Generated by Django 5.2.12 on 2026-04-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_patient_father_name_patient_mother_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientid',
            name='id_type',
            field=models.CharField(choices=[('ELEITORAL', 'Eleitoral (National ID)'), ('BI', 'BI (Bilhete de Identidade)'), ('PASSPORT', 'Passport'), ('OTHER', 'Other')], max_length=20, verbose_name='ID Type'),
        ),
    ]
