# Generated by Django 5.2.12 on 2026-04-12 03:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_patient_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='Blood Type'),
        ),
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allergen', models.CharField(max_length=200, verbose_name='Allergen')),
                ('reaction', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reaction')),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], default='MILD', max_length=10, verbose_name='Severity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('noted_date', models.DateField(auto_now_add=True, verbose_name='Date Noted')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient Allergy',
                'verbose_name_plural': 'Patient Allergies',
                'ordering': ['-noted_date'],
            },
        ),
    ]
