# Generated by Django 5.2.12 on 2026-04-16 01:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_patient_blood_type_patientallergy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyqueue',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='dailyqueue',
            unique_together={('date', 'department')},
        ),
    ]
