# Generated by Django 5.2.12 on 2026-04-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_alter_dailyqueue_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aldeia',
            options={'ordering': ['name'], 'verbose_name': 'Hamlet (Aldeia)', 'verbose_name_plural': 'Hamlets (Aldeias)'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ['name'], 'verbose_name': 'Municipality', 'verbose_name_plural': 'Municipalities'},
        ),
        migrations.AlterModelOptions(
            name='postoadministrativo',
            options={'ordering': ['name'], 'verbose_name': 'Administrative Post', 'verbose_name_plural': 'Administrative Posts'},
        ),
        migrations.AlterModelOptions(
            name='suco',
            options={'ordering': ['name'], 'verbose_name': 'Village (Suco)', 'verbose_name_plural': 'Villages (Sucos)'},
        ),
        migrations.AlterField(
            model_name='aldeia',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Hamlet (Aldeia)'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Municipality'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_category',
            field=models.CharField(choices=[('RAI_LARAN', 'Local'), ('RAI_LIUR', 'International')], default='RAI_LARAN', max_length=10, verbose_name='Patient Category'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Contribution (USD)'),
        ),
        migrations.AlterField(
            model_name='patientid',
            name='id_type',
            field=models.CharField(choices=[('ELEITORAL', 'National ID (Eleitoral)'), ('BI', 'Identity Card (BI)'), ('PASSPORT', 'Passport'), ('OTHER', 'Other')], max_length=20, verbose_name='ID Type'),
        ),
        migrations.AlterField(
            model_name='postoadministrativo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Administrative Post'),
        ),
        migrations.AlterField(
            model_name='suco',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Village (Suco)'),
        ),
    ]
