# Generated by Django 5.2.12 on 2026-04-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_alter_aldeia_options_alter_municipio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_hiv_patient',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is HIV Patient'),
        ),
    ]
