# Generated by Django 5.2.12 on 2026-04-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_patient_is_hiv_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_tb_patient',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is TB Patient'),
        ),
    ]
