# Generated by Django 5.2.12 on 2026-04-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_patient_is_tb_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_lactating',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Lactating'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_pregnant',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Pregnant'),
        ),
    ]
