# Generated by Django 5.2.12 on 2026-04-28 02:37

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_patient_is_lactating_patient_is_pregnant'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patient',
            index=django.contrib.postgres.indexes.GinIndex(fields=['patient_id'], name='idx_patient_id_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
