# Generated by Django 5.2.12 on 2026-04-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0021_fix_test_patient_visibility'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['municipio'], name='idx_patient_municipio'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['posto_administrativo'], name='idx_patient_posto'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['suco'], name='idx_patient_suco'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['aldeia'], name='idx_patient_aldeia'),
        ),
    ]
