# Generated by Django 5.2.12 on 2026-04-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_patient_idx_patient_municipio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_address',
            field=models.TextField(blank=True, null=True, verbose_name='Emergency Contact Address'),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Emergency Contact Relation'),
        ),
    ]
