# Generated by Django 5.2.12 on 2026-05-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0023_patient_emergency_contact_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='qr_code_data',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='QR Code Data'),
        ),
    ]
