# Generated by Django 5.2.12 on 2026-03-11 00:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('queue_number', models.PositiveIntegerField()),
                ('complaint', models.TextField(verbose_name='Keluhan Utama')),
                ('vital_signs', models.JSONField(default=dict, help_text='BP, Temp, Weight, etc.')),
                ('diagnosis_icd10', models.CharField(blank=True, max_length=20, null=True)),
                ('clinical_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCH', 'Scheduled'), ('IP', 'In Progress'), ('COM', 'Completed'), ('CAN', 'Cancelled')], default='SCH', max_length=3)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_visits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
        ),
    ]
