# Generated by Django 5.2.12 on 2026-03-11 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
        ('patients', '0002_alter_patient_address_alter_patient_date_of_birth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='clinical_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Clinical Notes'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='complaint',
            field=models.TextField(verbose_name='Chief Complaint'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='diagnosis_icd10',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diagnosis (ICD-10)'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_visits', to=settings.AUTH_USER_MODEL, verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='queue_number',
            field=models.PositiveIntegerField(verbose_name='Queue Number'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('SCH', 'Scheduled'), ('IP', 'In Progress'), ('COM', 'Completed'), ('CAN', 'Cancelled')], default='SCH', max_length=3, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Visit Date'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='vital_signs',
            field=models.JSONField(default=dict, help_text='BP, Temp, Weight, etc.', verbose_name='Vital Signs'),
        ),
    ]
