# Generated by Django 5.2.12 on 2026-03-18 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_alter_visit_clinical_notes_alter_visit_complaint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='ICD-10 Code')),
                ('name', models.CharField(max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Diagnosis',
                'verbose_name_plural': 'Diagnoses',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='visit',
            name='diagnosis_icd10',
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_records.diagnosis', verbose_name='Diagnosis (ICD-10)'),
        ),
    ]
