# Generated by Django 5.2.12 on 2026-03-19 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0003_diagnosis_remove_visit_diagnosis_icd10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Room Name')),
                ('code', models.CharField(help_text='e.g., ROOM_1, TRIAGE, LAB', max_length=20, unique=True, verbose_name='Room Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='bp_dia',
            field=models.IntegerField(blank=True, null=True, verbose_name='BP Diastolic'),
        ),
        migrations.AddField(
            model_name='visit',
            name='bp_sys',
            field=models.IntegerField(blank=True, null=True, verbose_name='BP Systolic'),
        ),
        migrations.AddField(
            model_name='visit',
            name='muac',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='MUAC (cm)'),
        ),
        migrations.AddField(
            model_name='visit',
            name='pulse',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pulse (bpm)'),
        ),
        migrations.AddField(
            model_name='visit',
            name='rr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Respiratory Rate (bpm)'),
        ),
        migrations.AddField(
            model_name='visit',
            name='spo2',
            field=models.IntegerField(blank=True, null=True, verbose_name='SPO2 (%)'),
        ),
        migrations.AddField(
            model_name='visit',
            name='temp',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperature (°C)'),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Visit Fee (USD)'),
        ),
        migrations.AddField(
            model_name='visit',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='complaint',
            field=models.TextField(blank=True, null=True, verbose_name='Chief Complaint'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='vital_signs',
            field=models.JSONField(blank=True, default=dict, help_text='Additional vital signs or notes.', verbose_name='Vital Signs (Legacy/Notes)'),
        ),
        migrations.AddField(
            model_name='visit',
            name='current_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_visits', to='medical_records.room', verbose_name='Current Room'),
        ),
    ]
