# Generated by Django 5.2.12 on 2026-03-23 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0004_room_visit_bp_dia_visit_bp_sys_visit_muac_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'permissions': [('can_print_visit', 'Can print visit report/summary'), ('can_export_visits', 'Can export visit data'), ('view_menu_medical_records', 'Can see Medical Records menu in sidebar')], 'verbose_name': 'Visit', 'verbose_name_plural': 'Visits'},
        ),
    ]
