# Generated by Django 5.2.12 on 2026-03-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0005_alter_visit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='lab_cbc',
            field=models.BooleanField(default=False, verbose_name='Request CBC (Lab)'),
        ),
        migrations.AddField(
            model_name='visit',
            name='pharmacy_requested',
            field=models.BooleanField(default=False, verbose_name='Request Pharmacy'),
        ),
        migrations.AddField(
            model_name='visit',
            name='refer_to_central',
            field=models.BooleanField(default=False, verbose_name='Refer to Central Facility'),
        ),
    ]
