# Generated by Django 5.2.12 on 2026-03-29 05:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0006_visit_lab_cbc_visit_pharmacy_requested_and_more'),
        ('patients', '0007_patient_idx_patient_fullname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['visit_date', 'status'], name='idx_visit_date_status'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['current_room', 'status'], name='idx_visit_room_status'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['patient', '-visit_date'], name='idx_visit_patient_date'),
        ),
    ]
