# Generated by Django 5.2.12 on 2026-03-29 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0007_visit_idx_visit_date_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_visits', to=settings.AUTH_USER_MODEL, verbose_name='Checked In By'),
        ),
        migrations.AddField(
            model_name='visit',
            name='triage_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_visits', to=settings.AUTH_USER_MODEL, verbose_name='Triage Nurse'),
        ),
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CHECK_IN', 'Check-In'), ('TRIAGE', 'Triage'), ('EXAMINATION', 'Doctor Examination'), ('LAB_REQUEST', 'Lab Request Created'), ('LAB_RESULT', 'Lab Result Entered'), ('RAD_REQUEST', 'Radiology Request Created'), ('RAD_RESULT', 'Radiology Result Entered'), ('PATHO_REQUEST', 'Pathology Request Created'), ('PATHO_RESULT', 'Pathology Result Entered'), ('PRESCRIPTION', 'Prescription Created'), ('DISPENSED', 'Medicine Dispensed'), ('REFERRED', 'Referred to National'), ('COMPLETED', 'Visit Completed'), ('STATUS_CHANGE', 'Status Changed')], max_length=20, verbose_name='Action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_records.room', verbose_name='Room')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='medical_records.visit', verbose_name='Visit')),
            ],
            options={
                'verbose_name': 'Visit Log',
                'verbose_name_plural': 'Visit Logs',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['visit', 'timestamp'], name='idx_visitlog_visit_ts')],
            },
        ),
    ]
