# Generated by Django 5.2.12 on 2026-04-07 23:53

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0008_visit_checked_in_by_visit_triage_nurse_visitlog'),
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.AddIndex(
            model_name='room',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='idx_room_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='idx_diag_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=django.contrib.postgres.indexes.GinIndex(fields=['code'], name='idx_diag_code_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=django.contrib.postgres.indexes.GinIndex(fields=['complaint'], name='idx_visit_complaint_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
