# Generated by Django 5.2.12 on 2026-04-11 03:40

import clinic_core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0009_diagnosis_idx_diag_name_trgm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='clinical_notes',
            field=clinic_core.fields.EncryptedTextField(blank=True, null=True, verbose_name='Clinical Notes'),
        ),
    ]
