# Generated by Django 5.2.12 on 2026-04-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0010_alter_visit_clinical_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='patient_type',
            field=models.CharField(choices=[('FOUN', 'FOUN (New Patient)'), ('TUAN', 'TUAN (Old Patient)')], default='FOUN', max_length=4, verbose_name='Patient Type'),
        ),
    ]
