# Generated by Django 5.2.12 on 2026-04-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0011_visit_patient_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='category',
            field=models.CharField(choices=[('COMM', 'Communicable Disease (Menular)'), ('NON_COMM', 'Non-Communicable Disease (Tidak Menular)'), ('OTHER', 'Other')], default='OTHER', max_length=10, verbose_name='Category'),
        ),
    ]
