# Generated by Django 5.2.12 on 2026-04-11 06:13 (customized to handle data migration)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0012_diagnosis_category'),
    ]

    operations = [
        # Step 1: Create the new DiagnosisCategory table
        migrations.CreateModel(
            name='DiagnosisCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Diagnosis Category',
                'verbose_name_plural': 'Diagnosis Categories',
            },
        ),

        # Step 2: Add new FK column (nullable first, so no data conflict)
        migrations.AddField(
            model_name='diagnosis',
            name='category_fk',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='diagnoses',
                to='medical_records.diagnosiscategory',
                verbose_name='Category'
            ),
        ),

        # Step 3: Drop the old plain char column
        migrations.RemoveField(
            model_name='diagnosis',
            name='category',
        ),

        # Step 4: Rename the new FK column to 'category'
        migrations.RenameField(
            model_name='diagnosis',
            old_name='category_fk',
            new_name='category',
        ),
    ]
