# Generated by Django 5.2.12 on 2026-04-11 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0013_diagnosiscategory_alter_diagnosis_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'permissions': [('can_print_visit', 'Can print visit report/summary'), ('can_export_visits', 'Can export visit data'), ('view_menu_medical_records', 'Can see Medical Records menu in sidebar'), ('view_menu_specialist_kia', 'Can see KIA menu in sidebar'), ('view_menu_specialist_hiv', 'Can see HIV menu in sidebar'), ('view_menu_specialist_tb', 'Can see TB menu in sidebar'), ('view_menu_specialist_dental', 'Can see Dental menu in sidebar'), ('view_menu_specialist_nutrition', 'Can see Nutrition menu in sidebar')], 'verbose_name': 'Visit', 'verbose_name_plural': 'Visits'},
        ),
    ]
