# Generated by Django 5.2.12 on 2026-04-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0014_alter_visit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='discharge_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Discharge Date/Time'),
        ),
        migrations.AddField(
            model_name='visit',
            name='discharge_summary',
            field=models.TextField(blank=True, null=True, verbose_name='Discharge Summary'),
        ),
        migrations.AddField(
            model_name='visit',
            name='secondary_diagnoses',
            field=models.ManyToManyField(blank=True, related_name='secondary_visits', to='medical_records.diagnosis', verbose_name='Secondary Diagnoses'),
        ),
    ]
