# Generated by Django 5.2.12 on 2026-04-12 15:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0015_visit_discharge_datetime_visit_discharge_summary_and_more'),
        ('pharmacy', '0008_medicine_idx_med_name_trgm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='arrival_mode',
            field=models.CharField(choices=[('AMBULANCE', 'Ambulance'), ('PRIVATE', 'Private Vehicle'), ('POLICE', 'Police/Military'), ('G_SUCO', 'Government/Suco Vehicle'), ('WALK_IN', 'Walk-in')], default='WALK_IN', max_length=20, verbose_name='Arrival Mode'),
        ),
        migrations.AddField(
            model_name='visit',
            name='arrival_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Arrival Details'),
        ),
        migrations.AddField(
            model_name='visit',
            name='brought_by_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Brought By (Person)'),
        ),
        migrations.AddField(
            model_name='visit',
            name='companion_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Companion Name'),
        ),
        migrations.AddField(
            model_name='visit',
            name='discharge_condition',
            field=models.CharField(blank=True, choices=[('IMPROVED', 'Improved (Kondisaun Diak)'), ('STABLE', 'Stable (Estavel)'), ('REFERRED', 'Referred (Referidu)'), ('APS', 'APS (Against Medical Advice)'), ('KABUR', 'Kabur (Eloped/Ran Away)'), ('DECEASED', 'Deceased (Mate)')], max_length=20, null=True, verbose_name='Discharge Condition'),
        ),
        migrations.AddField(
            model_name='visit',
            name='referral_hospital',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Referred to Hospital'),
        ),
        migrations.AddField(
            model_name='visit',
            name='referral_vehicle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Referral Vehicle Info'),
        ),
        migrations.AddField(
            model_name='visit',
            name='triage_level',
            field=models.CharField(blank=True, choices=[('RED', 'RED (Immediate/Critical)'), ('YELLOW', 'YELLOW (Urgent/Observation)'), ('GREEN', 'GREEN (Stable/Walking)'), ('BLACK', 'BLACK (Deceased/Non-viable)')], max_length=10, null=True, verbose_name='Triage Level'),
        ),
        migrations.CreateModel(
            name='EmergencyMedication',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity Given')),
                ('admin_type', models.CharField(choices=[('ORAL', 'Oral (Minum Biasa)'), ('INJECTION', 'Injection (Cuntik)'), ('OXYGEN', 'Oxygen (Ogsigen)'), ('IV_FLUIDS', 'IV Fluids / Sinfus'), ('TOPICAL', 'Topical')], default='ORAL', max_length=20, verbose_name='Administration Type')),
                ('dosage_instruction', models.CharField(help_text='e.g. 500mg, 1 ampoule, 2L/min', max_length=255, verbose_name='Dose & Instruction')),
                ('given_at', models.DateTimeField(auto_now_add=True, verbose_name='Time Administered')),
                ('given_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administered By (Doctor/Nurse)')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergency_administrations', to='pharmacy.medicine', verbose_name='Medicine')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_medications', to='medical_records.visit', verbose_name='Visit')),
            ],
            options={
                'verbose_name': 'Emergency Medication',
                'verbose_name_plural': 'Emergency Medications',
                'ordering': ['-given_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyObservation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Observation Time')),
                ('bp_sys', models.IntegerField(blank=True, null=True, verbose_name='BP Systolic')),
                ('bp_dia', models.IntegerField(blank=True, null=True, verbose_name='BP Diastolic')),
                ('spo2', models.IntegerField(blank=True, null=True, verbose_name='SPO2 (%)')),
                ('pulse', models.IntegerField(blank=True, null=True, verbose_name='Pulse (bpm)')),
                ('rr', models.IntegerField(blank=True, null=True, verbose_name='Respiratory Rate (bpm)')),
                ('temp', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperature (°C)')),
                ('clinical_notes', models.TextField(blank=True, null=True, verbose_name='Observation Progress Notes')),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Monitored By')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='medical_records.visit', verbose_name='Visit')),
            ],
            options={
                'verbose_name': 'Emergency Observation',
                'verbose_name_plural': 'Emergency Observations',
                'ordering': ['-check_time'],
            },
        ),
    ]
