# Generated by Django 5.2.12 on 2026-04-15 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0016_visit_arrival_mode_visit_arrival_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='continuation_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='continuations', to='medical_records.visit', verbose_name='Continuation Of'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('SCH', 'Scheduled'), ('IP', 'In Progress'), ('COM', 'Completed'), ('CAN', 'Cancelled'), ('UNC', 'Uncompleted/Expired')], default='SCH', max_length=3, verbose_name='Status'),
        ),
    ]
