# Generated by Django 5.2.12 on 2026-04-15 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0017_visit_continuation_of_alter_visit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencymedication',
            name='ordered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Ordered By (Doctor)'),
        ),
        migrations.AlterField(
            model_name='emergencymedication',
            name='given_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administered By (Nurse)'),
        ),
    ]
