# Generated by Django 5.2.12 on 2026-04-16 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0018_emergencymedication_ordered_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencymedication',
            name='admin_type',
            field=models.CharField(choices=[('ORAL', 'Oral'), ('INJECTION', 'Injection'), ('OXYGEN', 'Oxygen'), ('IV_FLUIDS', 'IV Fluids'), ('TOPICAL', 'Topical')], default='ORAL', max_length=20, verbose_name='Administration Type'),
        ),
        migrations.AlterField(
            model_name='emergencymedication',
            name='given_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administered By (Nurse)'),
        ),
        migrations.AlterField(
            model_name='emergencyobservation',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Monitored By'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='discharge_condition',
            field=models.CharField(blank=True, choices=[('IMPROVED', 'Improved'), ('STABLE', 'Stable'), ('REFERRED', 'Referred'), ('APS', 'Against Medical Advice (APS)'), ('KABUR', 'Eloped / Ran Away'), ('DECEASED', 'Deceased')], max_length=20, null=True, verbose_name='Discharge Condition'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient_type',
            field=models.CharField(choices=[('FOUN', 'New Patient'), ('TUAN', 'Returning Patient')], default='FOUN', max_length=4, verbose_name='Patient Type'),
        ),
    ]
