# Generated by Django 5.2.12 on 2026-04-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0019_alter_emergencymedication_admin_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True, verbose_name='Follow-up Date'),
        ),
        migrations.AddField(
            model_name='visit',
            name='follow_up_notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Follow-up Notes'),
        ),
    ]
