# Generated by Django 5.2.12 on 2026-04-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0020_visit_follow_up_date_visit_follow_up_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='ICD-10 Code'),
        ),
    ]
