# Generated by Django 5.2.12 on 2026-04-19 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0021_alter_diagnosis_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_types', to='medical_records.diagnosis', verbose_name='Parent Diagnosis'),
        ),
    ]
