# Generated by Django 5.2.12 on 2026-04-22 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0022_diagnosis_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyobservation',
            name='vas_score',
            field=models.CharField(blank=True, choices=[('0', '0 (No Pain)'), ('1-3', '1-3 (Mild)'), ('4-6', '4-6 (Moderate)'), ('7-9', '7-9 (Severe)'), ('10', '10 (Worst Pain)')], max_length=5, null=True, verbose_name='VAS Pain Score'),
        ),
        migrations.AddField(
            model_name='visit',
            name='er_bp_dia',
            field=models.IntegerField(blank=True, null=True, verbose_name='ER BP Diastolic'),
        ),
        migrations.AddField(
            model_name='visit',
            name='er_bp_sys',
            field=models.IntegerField(blank=True, null=True, verbose_name='ER BP Systolic'),
        ),
        migrations.AddField(
            model_name='visit',
            name='er_muac',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='ER MUAC (cm)'),
        ),
        migrations.AddField(
            model_name='visit',
            name='er_pulse',
            field=models.IntegerField(blank=True, null=True, verbose_name='ER Pulse (bpm)'),
        ),
        migrations.AddField(
            model_name='visit',
            name='er_rr',
            field=models.IntegerField(blank=True, null=True, verbose_name='ER Respiratory Rate'),
        ),
        migrations.AddField(
            model_name='visit',
            name='er_spo2',
            field=models.IntegerField(blank=True, null=True, verbose_name='ER SPO2 (%)'),
        ),
        migrations.AddField(
            model_name='visit',
            name='er_temp',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='ER Temperature (°C)'),
        ),
        migrations.AddField(
            model_name='visit',
            name='er_weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='ER Weight (kg)'),
        ),
        migrations.AddField(
            model_name='visit',
            name='vas_score',
            field=models.CharField(blank=True, choices=[('0', '0 (No Pain)'), ('1-3', '1-3 (Mild)'), ('4-6', '4-6 (Moderate)'), ('7-9', '7-9 (Severe)'), ('10', '10 (Worst Pain)')], max_length=5, null=True, verbose_name='VAS Pain Score'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Diagnosis Code'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leave blank if this is a Top-level Category (Parent)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_types', to='medical_records.diagnosis', verbose_name='Parent Diagnosis'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_records.diagnosis', verbose_name='Diagnosis'),
        ),
    ]
