# Generated by Django 5.2.12 on 2026-04-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0023_emergencyobservation_vas_score_visit_er_bp_dia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='source',
            field=models.CharField(choices=[('OPD', 'OPD (Outpatient)'), ('IGD', 'IGD (Emergency)')], default='OPD', max_length=3, verbose_name='Source'),
        ),
    ]
