# Generated by Django 5.2.12 on 2026-04-29 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0026_alter_visit_options'),
        ('patients', '0022_patient_idx_patient_municipio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['diagnosis'], name='idx_visit_diagnosis'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['patient'], name='idx_visit_patient'),
        ),
    ]
