# Generated by Django 5.2.12 on 2026-04-30 01:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0027_visit_idx_visit_diagnosis_visit_idx_visit_patient'),
        ('patients', '0022_patient_idx_patient_municipio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HIVAssessment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_registered_at_bpc', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date of registration at BPC')),
                ('patient_type', models.CharField(choices=[('NEW', 'New patient'), ('TRANSFER', 'Transfer in')], default='NEW', max_length=10, verbose_name='Patient Type')),
                ('previous_registrations', models.CharField(blank=True, max_length=255, null=True, verbose_name='Previous registrations (if applicable)')),
                ('previous_art', models.CharField(blank=True, max_length=255, null=True, verbose_name='Previous ART (if applicable)')),
                ('first_positive_test_date', models.DateField(blank=True, null=True, verbose_name='Date of first positive test')),
                ('confirmation_test_seen', models.BooleanField(default=False, verbose_name='Confirmation test seen?')),
                ('where_test_done', models.CharField(blank=True, max_length=255, null=True, verbose_name='Where test done')),
                ('prophylaxis_inh', models.BooleanField(default=False, help_text='All new patients unless active TB', verbose_name='INH')),
                ('prophylaxis_cotrimoxazole', models.BooleanField(default=False, help_text='adults CD4<350 or TB, children <5', verbose_name='Co-trimoxazole')),
                ('prophylaxis_fluconazole', models.BooleanField(default=False, help_text='crypto meningitis treated or CD4<100 and CrAg+', verbose_name='Fluconazole')),
                ('investigation_tb_needed', models.TextField(blank=True, null=True, verbose_name='Further investigation for TB needed?')),
                ('contraception_plans', models.TextField(blank=True, null=True, verbose_name='Plans for contraception')),
                ('planned_for_art', models.BooleanField(default=False, verbose_name='Is the patient planned for ART?')),
                ('art_regime', models.CharField(blank=True, max_length=255, null=True, verbose_name='ART Regime')),
                ('next_visit_scheduled', models.DateField(blank=True, null=True, verbose_name='Next visit scheduled')),
                ('other_plans', models.TextField(blank=True, null=True, verbose_name='Plans / investigations / others')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Completed by')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiv_assessments', to='patients.patient', verbose_name='Patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hiv_assessments', to='medical_records.visit', verbose_name='Visit')),
            ],
            options={
                'verbose_name': 'HIV Assessment',
                'verbose_name_plural': 'HIV Assessments',
                'ordering': ['-created_at'],
            },
        ),
    ]
