# Generated by Django 5.2.12 on 2026-05-01 07:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0028_hivassessment'),
        ('patients', '0023_patient_emergency_contact_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TBScreening',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True, verbose_name='Gender')),
                ('outreach_location', models.CharField(blank=True, help_text='e.g. Market, School, Church', max_length=255, null=True, verbose_name='Specific Location/Site')),
                ('has_cough_2_weeks', models.BooleanField(default=False, verbose_name='Cough > 2 Weeks')),
                ('has_fever', models.BooleanField(default=False, verbose_name='Fever')),
                ('has_night_sweats', models.BooleanField(default=False, verbose_name='Night Sweats')),
                ('has_weight_loss', models.BooleanField(default=False, verbose_name='Unexplained Weight Loss')),
                ('has_contact_history', models.BooleanField(default=False, verbose_name='Contact with TB Patient')),
                ('is_hiv_positive', models.BooleanField(default=False, verbose_name='Known HIV Positive')),
                ('is_suspect', models.BooleanField(default=False, verbose_name='Is TB Suspect')),
                ('referral_status', models.CharField(choices=[('NONE', 'No Referral'), ('CLINIC', 'Referred to Clinic'), ('LAB', 'Referred to Lab (Sputum)')], default='NONE', max_length=10, verbose_name='Referral Status')),
                ('sputum_collected', models.BooleanField(default=False, verbose_name='Sputum Sample Collected on Site')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('screening_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Screening Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aldeia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.aldeia')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.municipio')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tb_screenings', to='patients.patient', verbose_name='Registered Patient')),
                ('posto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.postoadministrativo')),
                ('screened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_tb_screenings', to=settings.AUTH_USER_MODEL)),
                ('suco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.suco')),
            ],
            options={
                'verbose_name': 'TB Screening Outreach',
                'verbose_name_plural': 'TB Screening Outreach Logs',
                'ordering': ['-screening_date', '-created_at'],
                'indexes': [models.Index(fields=['screening_date', 'is_suspect'], name='medical_rec_screeni_7b0884_idx'), models.Index(fields=['suco', 'aldeia'], name='medical_rec_suco_id_e24875_idx')],
            },
        ),
    ]
