# Generated by Django 5.2.12 on 2026-05-02 10:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0030_tbscreening_lab_result_tbscreening_lab_test_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitDiagnosis',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Diagnosis')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Specific Diagnosis Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visit Diagnosis',
                'verbose_name_plural': 'Visit Diagnoses',
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp_sys', models.IntegerField(blank=True, null=True, verbose_name='BP Systolic')),
                ('bp_dia', models.IntegerField(blank=True, null=True, verbose_name='BP Diastolic')),
                ('spo2', models.IntegerField(blank=True, null=True, verbose_name='SPO2 (%)')),
                ('pulse', models.IntegerField(blank=True, null=True, verbose_name='Pulse (bpm)')),
                ('rr', models.IntegerField(blank=True, null=True, verbose_name='Respiratory Rate (bpm)')),
                ('temp', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperature (°C)')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Weight (kg)')),
                ('muac', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='MUAC (cm)')),
                ('vas_score', models.CharField(blank=True, choices=[('0', '0 (No Pain)'), ('1-3', '1-3 (Mild)'), ('4-6', '4-6 (Moderate)'), ('7-9', '7-9 (Severe)'), ('10', '10 (Worst Pain)')], max_length=5, null=True, verbose_name='VAS Pain Score')),
                ('er_bp_sys', models.IntegerField(blank=True, null=True, verbose_name='ER BP Systolic')),
                ('er_bp_dia', models.IntegerField(blank=True, null=True, verbose_name='ER BP Diastolic')),
                ('er_spo2', models.IntegerField(blank=True, null=True, verbose_name='ER SPO2 (%)')),
                ('er_pulse', models.IntegerField(blank=True, null=True, verbose_name='ER Pulse (bpm)')),
                ('er_temp', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='ER Temperature (°C)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Vitals Notes')),
                ('taken_at', models.DateTimeField(auto_now_add=True, verbose_name='Time Taken')),
            ],
            options={
                'verbose_name': 'Vital Signs',
                'verbose_name_plural': 'Vital Signs',
            },
        ),
        migrations.RemoveIndex(
            model_name='visit',
            name='idx_visit_diagnosis',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='bp_dia',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='bp_sys',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='er_bp_dia',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='er_bp_sys',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='er_muac',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='er_pulse',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='er_rr',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='er_spo2',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='er_temp',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='er_weight',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='muac',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='pulse',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='rr',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='secondary_diagnoses',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='spo2',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='vas_score',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='vital_signs',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='weight',
        ),
        migrations.AddField(
            model_name='visitdiagnosis',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_records', to='medical_records.diagnosis'),
        ),
        migrations.AddField(
            model_name='visitdiagnosis',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_diagnoses', to='medical_records.visit'),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='medical_records.visit', verbose_name='Visit'),
        ),
        migrations.AlterUniqueTogether(
            name='visitdiagnosis',
            unique_together={('visit', 'diagnosis')},
        ),
    ]
