# Generated by Django 5.2.12 on 2026-05-02 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0031_visitdiagnosis_vitalsigns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns',
            name='visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs_record', to='medical_records.visit', verbose_name='Visit'),
        ),
    ]
