# Generated by Django 5.2.12 on 2026-05-02 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0032_alter_vitalsigns_visit'),
        ('patients', '0023_patient_emergency_contact_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsigns',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Height (cm)'),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='kia_category',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='MCH Category'),
        ),
        migrations.AlterField(
            model_name='hivassessment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiv_assessments', to='patients.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient', verbose_name='Patient'),
        ),
    ]
