# Generated by Django 5.2.12 on 2026-05-04 05:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0033_vitalsigns_height_cm_vitalsigns_kia_category_and_more'),
        ('patients', '0024_patient_qr_code_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TBCase',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tb_registration_number', models.CharField(help_text='National TB Program Number', max_length=50, unique=True, verbose_name='TB Reg Number')),
                ('date_started', models.DateField(verbose_name='Treatment Start Date')),
                ('case_type', models.CharField(choices=[('PTB_POS', 'PTB+ (Pulmonary TB Sputum Positive)'), ('PTB_NEG', 'PTB- (Pulmonary TB Sputum Negative)'), ('EPTB', 'EPTB (Extra-Pulmonary TB)')], max_length=10, verbose_name='Case Type')),
                ('category', models.CharField(choices=[('CAT_I', 'Category I (New Cases)'), ('CAT_II', 'Category II (Previously Treated)'), ('CAT_P', 'Pediatric (Children)'), ('CAT_MDR', 'MDR-TB')], max_length=10, verbose_name='Treatment Category')),
                ('initial_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight at Start (kg)')),
                ('site_of_eptb', models.CharField(blank=True, max_length=100, null=True, verbose_name='Site (if EPTB)')),
                ('sputum_month_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sputum Result (Month 2)')),
                ('sputum_month_5', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sputum Result (Month 5)')),
                ('sputum_month_6', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sputum Result (Month 6)')),
                ('outcome', models.CharField(choices=[('PENDING', 'Still on Treatment'), ('CURED', 'Cured'), ('COMPLETED', 'Treatment Completed'), ('DIED', 'Died'), ('FAILED', 'Treatment Failed'), ('LOST', 'Lost to Follow-up'), ('TRANSFERRED', 'Transferred Out')], default='PENDING', max_length=15, verbose_name='Treatment Outcome')),
                ('date_of_outcome', models.DateField(blank=True, null=True, verbose_name='Date of Outcome')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Clinical Notes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tb_cases', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'TB Case / Treatment Card',
                'verbose_name_plural': 'TB Cases',
                'ordering': ['-date_started'],
            },
        ),
        migrations.CreateModel(
            name='TBTreatmentLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_recorded', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('phase', models.CharField(choices=[('INTENSIVE', 'Intensive Phase'), ('CONTINUATION', 'Continuation Phase')], max_length=15, verbose_name='Phase')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight (kg)')),
                ('drugs_given', models.CharField(help_text='e.g. RHZE, RH', max_length=255, verbose_name='Drugs Given')),
                ('days_supply', models.PositiveIntegerField(default=30, verbose_name='Days of Supply Given')),
                ('side_effects', models.TextField(blank=True, null=True, verbose_name='Side Effects Noted')),
                ('is_missed_dose', models.BooleanField(default=False, verbose_name='Missed Doses?')),
                ('next_appointment', models.DateField(blank=True, null=True, verbose_name='Next Drug Collection Date')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
                ('tb_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='medical_records.tbcase', verbose_name='TB Case')),
                ('visit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_records.visit', verbose_name='Associated Visit')),
            ],
            options={
                'verbose_name': 'TB Treatment Log',
                'verbose_name_plural': 'TB Treatment Logs',
                'ordering': ['-date_recorded'],
            },
        ),
    ]
