# Generated by Django 5.2.12 on 2026-05-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0034_tbcase_tbtreatmentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcase',
            name='classification',
            field=models.CharField(choices=[('P', 'Pulmonar'), ('EP', 'Estra-Pulmuar')], default='P', max_length=2),
        ),
        migrations.AddField(
            model_name='tbcase',
            name='diabetes_status',
            field=models.CharField(blank=True, help_text='Diabetes Status (FBS/RBG)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbcase',
            name='hiv_status',
            field=models.CharField(blank=True, help_text='Teste HIV / Data / Rezultadu', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbcase',
            name='initial_sputum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbcase',
            name='initial_xray',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbcase',
            name='patient_type',
            field=models.CharField(choices=[('FOUN', 'Foun (New)'), ('RELAPSU', 'Relapsu (Relapse)'), ('DEPOIS_LAKON', 'Depois lakon (After loss to follow up)'), ('FALHA', 'Falha (Failure)'), ('OUTRU', 'Outru (Other)')], default='FOUN', max_length=20),
        ),
        migrations.AddField(
            model_name='tbcase',
            name='regimen',
            field=models.CharField(blank=True, help_text='e.g., RHZE (150/75/400/275 mg)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbcase',
            name='date_of_outcome',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbcase',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbcase',
            name='outcome',
            field=models.CharField(blank=True, choices=[('CURA', 'Kura (Cured)'), ('KOMPLETU', 'Tratamentu Kompletu'), ('FALHA', 'Falha'), ('MATE', 'Mate (Died)'), ('LAKON', 'Lakon (Lost to follow up)'), ('TRANSFER', 'Transfer (Transferred out)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tbcase',
            name='site_of_eptb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
