# Generated by Django 5.2.12 on 2026-05-04 08:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0035_tbcase_classification_tbcase_diabetes_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TBDailyDose',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('is_observed', models.BooleanField(default=True, help_text='True = (✔), False = (-)', verbose_name='Observed?')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
                ('tb_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_doses', to='medical_records.tbcase', verbose_name='TB Case')),
            ],
            options={
                'verbose_name': 'TB Daily Dose',
                'verbose_name_plural': 'TB Daily Doses',
                'ordering': ['-date'],
                'unique_together': {('tb_case', 'date')},
            },
        ),
    ]
