# Generated by Django 5.2.12 on 2026-05-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0036_tbdailydose'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcase',
            name='card_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores additional form data (checkboxes, remarks, etc)'),
        ),
        migrations.AddField(
            model_name='tbdailydose',
            name='status',
            field=models.CharField(choices=[('DONE', '✔'), ('UNOBSERVED', '-'), ('MISSED', '0'), ('NONE', '')], default='NONE', max_length=10),
        ),
    ]
