# Generated by Django 5.2.12 on 2026-05-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0037_tbcase_card_data_tbdailydose_status'),
        ('patients', '0024_patient_qr_code_data'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tbcase',
            index=models.Index(fields=['tb_registration_number'], name='idx_tb_reg_num'),
        ),
        migrations.AddIndex(
            model_name='tbcase',
            index=models.Index(fields=['date_started'], name='idx_tb_date_started'),
        ),
        migrations.AddIndex(
            model_name='tbcase',
            index=models.Index(fields=['patient', '-date_started'], name='idx_tb_patient_date'),
        ),
        migrations.AddIndex(
            model_name='tbcase',
            index=models.Index(fields=['is_active'], name='idx_tb_active'),
        ),
    ]
