# Generated by Django 5.2.12 on 2026-03-29 05:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('medical_records', '0007_visit_idx_visit_date_status_and_more'),
        ('patients', '0007_patient_idx_patient_fullname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['-created_at'], name='idx_invoice_created'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['patient', '-created_at'], name='idx_invoice_patient'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='idx_invoice_status'),
        ),
    ]
