# Generated by Django 5.2.12 on 2026-04-07 23:53

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_idx_invoice_created_and_more'),
        ('medical_records', '0008_visit_checked_in_by_visit_triage_nurse_visitlog'),
        ('patients', '0008_patient_idx_patient_name_trgm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.AddIndex(
            model_name='invoice',
            index=django.contrib.postgres.indexes.GinIndex(fields=['invoice_number'], name='idx_invoice_num_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
