# Generated by Django 5.2.12 on 2026-04-09 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_idx_invoice_num_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.servicecategory', verbose_name='Category'),
        ),
    ]
