# Generated by Django 5.2.12 on 2026-05-02 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoiceitem_category'),
        ('pharmacy', '0013_alter_dispenseditem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='item_type',
            field=models.CharField(choices=[('SERVICE', 'Service / Consultation'), ('MEDICINE', 'Medicine / Pharmacy'), ('LAB', 'Laboratory Test'), ('OTHER', 'Other')], default='SERVICE', max_length=10, verbose_name='Item Type'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.medicine', verbose_name='Medicine'),
        ),
    ]
