# Generated by Django 5.2.12 on 2026-05-02 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoiceitem_item_type_invoiceitem_medicine'),
        ('medical_records', '0033_vitalsigns_height_cm_vitalsigns_kia_category_and_more'),
        ('patients', '0024_patient_qr_code_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='patients.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='medical_records.visit', verbose_name='Visit'),
        ),
    ]
