web: python manage.py collectstatic --no-input && python manage.py migrate && python import_production_data.py && python fix_cloud_perms.py && python regenerate_assets.py && gunicorn clinic_core.wsgi
