# Generated by Django 5.2.12 on 2026-03-26 07:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_records', '0006_visit_lab_cbc_visit_pharmacy_requested_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PathologyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Test Name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Pathology Test',
                'verbose_name_plural': 'Pathology Tests',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PathologyRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_request', models.DateTimeField(auto_now_add=True, verbose_name='Date Requested')),
                ('fasting', models.BooleanField(default=False, verbose_name='Fasting (Jejum)')),
                ('clinica_history', models.TextField(blank=True, null=True, verbose_name='Clinica History')),
                ('billing_type', models.CharField(choices=[('O', 'Outpatient'), ('I', 'Inpatient'), ('P', 'Private'), ('G', 'Government')], default='O', max_length=1, verbose_name='Billing')),
                ('tube_sst', models.CharField(blank=True, max_length=100, null=True, verbose_name='SST')),
                ('tube_edta', models.CharField(blank=True, max_length=100, null=True, verbose_name='EDTA')),
                ('tube_esr', models.CharField(blank=True, max_length=100, null=True, verbose_name='ESR')),
                ('tube_plain', models.CharField(blank=True, max_length=100, null=True, verbose_name='Plain')),
                ('tube_cit', models.CharField(blank=True, max_length=100, null=True, verbose_name='CIT')),
                ('tube_flok', models.CharField(blank=True, max_length=100, null=True, verbose_name='FLOK')),
                ('tube_msu', models.CharField(blank=True, max_length=100, null=True, verbose_name='MSU')),
                ('tube_swabs', models.CharField(blank=True, max_length=100, null=True, verbose_name='Swabs')),
                ('tube_pap', models.CharField(blank=True, max_length=100, null=True, verbose_name='PAP')),
                ('tube_other', models.CharField(blank=True, max_length=150, null=True, verbose_name='Other')),
                ('requesting_physician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathology_requests', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pathology_request', to='medical_records.visit', verbose_name='Visit')),
                ('tests', models.ManyToManyField(blank=True, to='pathology.pathologytest', verbose_name='Tests Requested')),
            ],
            options={
                'verbose_name': 'Pathology Request',
                'verbose_name_plural': 'Pathology Requests',
                'ordering': ['-date_of_request'],
            },
        ),
    ]
