# Generated by Django 5.2.12 on 2026-03-27 02:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pathologyrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='PathologyResult',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_text', models.TextField(blank=True, null=True, verbose_name='Result Details')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='pathology_results/', verbose_name='Attachment (PDF)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('pathology_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='pathology.pathologyrequest', verbose_name='Pathology Request')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_pathology_results', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'Pathology Result',
                'verbose_name_plural': 'Pathology Results',
            },
        ),
    ]
