# Generated by Django 5.2.12 on 2026-04-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0005_pathologytest_idx_pathtest_name_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathologyrequest',
            name='source',
            field=models.CharField(choices=[('OPD', 'OPD (Outpatient)'), ('IGD', 'IGD (Emergency)')], default='OPD', max_length=10, verbose_name='Source'),
        ),
    ]
