# Generated by Django 5.2.12 on 2026-03-25 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_records', '0005_alter_visit_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Test Name')),
                ('column_index', models.IntegerField(choices=[(1, 'Column 1'), (2, 'Column 2'), (3, 'Column 3')], default=1, verbose_name='Form Column')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Lab Test',
                'verbose_name_plural': 'Lab Tests',
                'ordering': ['column_index', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_request', models.DateTimeField(auto_now_add=True, verbose_name='Date of request')),
                ('lab_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lab No')),
                ('patient_type', models.CharField(choices=[('IN', 'IN-patient'), ('OUT', 'OUTpatient')], default='OUT', max_length=10, verbose_name='Patient Type')),
                ('urgency', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'URGENT')], default='NORMAL', max_length=10, verbose_name='Urgency')),
                ('special_category', models.CharField(blank=True, choices=[('TB_PT', 'TB pt.'), ('TB_SUSP', 'TB susp.'), ('ANC', 'ANC'), ('STI', 'STI'), ('OTHERS', 'Others')], max_length=20, null=True, verbose_name='Special Category')),
                ('others_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Others Note')),
                ('requesting_physician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requesting Physician')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_request', to='medical_records.visit', verbose_name='Visit')),
                ('tests', models.ManyToManyField(blank=True, to='laboratory.labtest', verbose_name='Test Requests')),
            ],
            options={
                'verbose_name': 'Lab Request',
                'verbose_name_plural': 'Lab Requests',
                'ordering': ['-date_of_request'],
            },
        ),
    ]
