# Generated by Django 5.2.12 on 2026-03-30 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_labrequest_processed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResultAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lab_results/', verbose_name='File')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('lab_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='laboratory.labresult', verbose_name='Lab Result')),
            ],
            options={
                'verbose_name': 'Lab Result Attachment',
                'verbose_name_plural': 'Lab Result Attachments',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
