# Generated by Django 5.2.12 on 2026-04-07 23:53

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_labresultattachment'),
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.AddIndex(
            model_name='labtest',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='idx_labtest_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=django.contrib.postgres.indexes.GinIndex(fields=['code'], name='idx_labtest_code_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
