# Generated by Django 5.2.12 on 2026-04-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_labtest_idx_labtest_name_trgm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='source',
            field=models.CharField(choices=[('OPD', 'OPD'), ('IGD', 'IGD')], default='OPD', max_length=3, verbose_name='Source'),
        ),
    ]
