# Generated by Django 5.2.12 on 2026-05-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0007_labtest_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='flag',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('LOW', 'Low')], default='NORMAL', max_length=10, verbose_name='Flag'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='is_abnormal',
            field=models.BooleanField(default=False, verbose_name='Is Abnormal'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='normal_range',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Normal Range'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit'),
        ),
    ]
