# Generated by Django 5.2.12 on 2026-05-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0008_labresult_flag_labresult_is_abnormal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labrequest',
            name='lab_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Lab No'),
        ),
    ]
