# Generated by Django 5.2.12 on 2026-05-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0009_alter_labrequest_lab_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
