# Generated by Django 5.2.12 on 2026-05-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0010_labrequest_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cancel Reason'),
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
