# Generated by Django 5.2.12 on 2026-05-06 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0011_labrequest_cancel_reason_alter_labrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_lab_requests', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled By'),
        ),
    ]
