# Generated by Django 5.2.12 on 2026-05-11 23:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0012_labrequest_cancelled_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['completed_at'], name='idx_labres_completed'),
        ),
    ]
