# Generated by Django 5.2.12 on 2026-03-23 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'permissions': [('can_export_staff', 'Can export staff data'), ('view_menu_staff', 'Can see Staff Management menu in sidebar'), ('view_menu_master_data', 'Can see Master Data menu in sidebar')], 'verbose_name': 'Staff Profile', 'verbose_name_plural': 'Staff Profiles'},
        ),
    ]
