# Generated by Django 5.2.12 on 2026-04-07 23:53

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staffprofile_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.AddIndex(
            model_name='department',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='idx_dept_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='staffcategory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='idx_staffcat_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['staff_id'], name='idx_staff_id_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['phone'], name='idx_staff_phone_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
