# Generated by Django 5.2.12 on 2026-03-26 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_records', '0006_visit_lab_cbc_visit_pharmacy_requested_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiologyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Test Name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Radiology Test',
                'verbose_name_plural': 'Radiology Tests',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RadiologyRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_request', models.DateTimeField(auto_now_add=True, verbose_name='Data Riquest')),
                ('requesting_physician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_requests', to=settings.AUTH_USER_MODEL, verbose_name='Medico')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='radiology_request', to='medical_records.visit', verbose_name='Visit')),
                ('tests', models.ManyToManyField(blank=True, to='radiology.radiologytest', verbose_name='Test Requests')),
            ],
            options={
                'verbose_name': 'Radiology Request',
                'verbose_name_plural': 'Radiology Requests',
                'ordering': ['-date_of_request'],
            },
        ),
    ]
