# Generated by Django 5.2.12 on 2026-03-29 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0002_radiologyrequest_status_radiologyresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyrequest',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_radiology_requests', to=settings.AUTH_USER_MODEL, verbose_name='Performed By'),
        ),
    ]
