# Generated by Django 5.2.12 on 2026-05-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0006_radiologyrequest_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyrequest',
            name='radiology_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Radiology No'),
        ),
    ]
