# Generated by Django 5.2.12 on 2026-05-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0007_radiologyrequest_radiology_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='radiologyrequest',
            name='date_of_request',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of Request'),
        ),
    ]
