# Generated by Django 5.2.12 on 2026-03-25 08:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_records', '0006_visit_lab_cbc_visit_pharmacy_requested_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('has_allergy', models.CharField(choices=[('IHA', 'Yes (Iha)'), ('LA_IHA', 'No (La Iha)')], default='LA_IHA', max_length=10, verbose_name='Alerjia')),
                ('allergy_medicine', models.CharField(blank=True, help_text='Specify medicine if allergy exists', max_length=255, null=True, verbose_name='Aimoruk (Medicine)')),
                ('prescription_text', models.TextField(help_text='Enter the complete prescription details here', verbose_name='R/ (Prescription Details)')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Doutor/a')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='medical_records.visit', verbose_name='Visit')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-date_created'],
            },
        ),
    ]
