# Generated by Django 5.2.12 on 2026-03-27 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dispensed At'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Dispensed By'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensing_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Dispensing Notes'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DISPENSING', 'Dispensing'), ('DISPENSED', 'Dispensed'), ('COLLECTED', 'Collected by Patient')], default='PENDING', max_length=20, verbose_name='Dispensing Status'),
        ),
    ]
