# Generated by Django 5.2.12 on 2026-03-27 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_prescription_dispensed_at_prescription_dispensed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Medicine Name')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code')),
                ('unit', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('BOTTLE', 'Bottle'), ('TUBE', 'Tube'), ('AMPOULE', 'Ampoule'), ('SACHET', 'Sachet'), ('ML', 'mL'), ('PIECE', 'Piece')], default='TABLET', max_length=20, verbose_name='Unit')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Current Stock')),
                ('min_stock', models.PositiveIntegerField(default=10, verbose_name='Minimum Stock Alert')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DispensedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('dosage_instructions', models.CharField(blank=True, help_text='e.g. 3x1 after meal', max_length=255, null=True, verbose_name='Dosage Instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensed_items', to='pharmacy.prescription', verbose_name='Prescription')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensed_items', to='pharmacy.medicine', verbose_name='Medicine')),
            ],
            options={
                'verbose_name': 'Dispensed Item',
                'verbose_name_plural': 'Dispensed Items',
                'unique_together': {('prescription', 'medicine')},
            },
        ),
    ]
