# Generated by Django 5.2.12 on 2026-03-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_stockentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='donor_name',
            field=models.CharField(blank=True, help_text='Name of donor, NGO, or government program', max_length=255, null=True, verbose_name='Donor / Organization Name'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='source_type',
            field=models.CharField(choices=[('PURCHASE', 'Clinic Purchase (Sosa Rasik)'), ('GOV_DONATION', 'Government Donation (Doasaun Governu)'), ('NGO_INT', 'International NGO Donation (ONG Internasional)'), ('NGO_NAT', 'National NGO Donation (ONG Nasional)'), ('VOLUNTEER', 'Volunteer Donation (Voluntariu)'), ('OTHER', 'Other (Seluk)')], default='PURCHASE', max_length=20, verbose_name='Source / Origem'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='purchase_date',
            field=models.DateField(verbose_name='Received Date / Data Simu'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Supplier / Vendor'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Set to 0 for donations', max_digits=10, verbose_name='Unit Price (USD)'),
        ),
    ]
