# Generated by Django 5.2.12 on 2026-03-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_stockentry_donor_name_stockentry_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='form',
            field=models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup (Xarope)'), ('INJECTION', 'Injection (Injeksaun)'), ('CREAM', 'Cream/Ointment (Krema)'), ('DROPS', 'Drops (Tetes)'), ('INHALER', 'Inhaler'), ('SUPPOSITORY', 'Suppository'), ('POWDER', 'Powder (Pozolok)'), ('SUSPENSION', 'Suspension'), ('OTHER', 'Other (Seluk)')], default='TABLET', max_length=20, verbose_name='Form / Sediaan'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='strength',
            field=models.CharField(blank=True, help_text='e.g. 500mg, 250mg, 125mg/5ml, 10mg/ml', max_length=50, null=True, verbose_name='Strength / Dosage'),
        ),
    ]
