# Generated by Django 5.2.12 on 2026-03-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_medicine_form_medicine_strength'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['name'], name='idx_medicine_name'),
        ),
    ]
