# Generated by Django 5.2.12 on 2026-04-07 23:53

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_medicine_idx_medicine_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.AddIndex(
            model_name='medicine',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='idx_med_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=django.contrib.postgres.indexes.GinIndex(fields=['code'], name='idx_med_code_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['batch_number'], name='idx_stock_batch_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['supplier'], name='idx_stock_supplier_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
