# Generated by Django 5.2.12 on 2026-04-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_medicine_idx_med_name_trgm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='is_hiv_medicine',
            field=models.BooleanField(default=False, verbose_name='HIV Specific Medicine'),
        ),
    ]
