# Generated by Django 5.2.12 on 2026-04-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_medicine_is_hiv_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='source',
            field=models.CharField(choices=[('OPD', 'OPD'), ('IGD', 'IGD')], default='OPD', max_length=3, verbose_name='Source'),
        ),
    ]
