# Generated by Django 5.2.12 on 2026-04-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_prescription_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='form',
            field=models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup (Xarope)'), ('INJECTION', 'Injection (Injeksaun)'), ('INFUSION', 'Infusion (Infus)'), ('CREAM', 'Cream/Ointment (Krema)'), ('DROPS', 'Drops (Tetes)'), ('INHALER', 'Inhaler'), ('SUPPOSITORY', 'Suppository'), ('POWDER', 'Powder (Pozolok)'), ('SUSPENSION', 'Suspension'), ('OTHER', 'Other (Seluk)')], default='TABLET', max_length=20, verbose_name='Form / Sediaan'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit',
            field=models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('BOTTLE', 'Bottle'), ('TUBE', 'Tube'), ('AMPOULE', 'Ampoule'), ('VIAL', 'Vial'), ('BAG', 'Bag / Kolf'), ('CYLINDER', 'Cylinder / Tabung'), ('SACHET', 'Sachet'), ('BOX', 'Box / Kotak'), ('ML', 'mL'), ('PIECE', 'Piece')], default='TABLET', max_length=20, verbose_name='Unit'),
        ),
    ]
