# Generated by Django 5.2.12 on 2026-04-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_alter_medicine_form_alter_medicine_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='is_hiv_medicine',
        ),
        migrations.AddField(
            model_name='medicine',
            name='department_category',
            field=models.CharField(choices=[('GENERAL', 'General Pharmacy'), ('HIV', 'HIV/AIDS Department'), ('TB', 'TB Department'), ('DENTAL', 'Dental Department'), ('KIA', 'MCH/KIA Department')], default='GENERAL', max_length=20, verbose_name='Department Category'),
        ),
    ]
