# Generated by Django 5.2.12 on 2026-05-02 10:55

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_remove_medicine_is_hiv_medicine_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dispenseditem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='stock',
        ),
        migrations.AddField(
            model_name='dispenseditem',
            name='dispensed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dispensed At'),
        ),
        migrations.AddField(
            model_name='dispenseditem',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dispensed By'),
        ),
        migrations.AddField(
            model_name='dispenseditem',
            name='quantity_dispensed',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity Dispensed'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Selling Price (USD)'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit',
            field=models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('BOTTLE', 'Bottle'), ('TUBE', 'Tube'), ('AMPOULE', 'Ampoule'), ('VIAL', 'Vial'), ('BAG', 'Bag / Kolf'), ('CYLINDER', 'Cylinder / Tabung'), ('SACHET', 'Sachet'), ('BOX', 'Box / Kotak'), ('ML', 'mL'), ('LITER', 'Liter (L)'), ('PIECE', 'Piece')], default='TABLET', max_length=20, verbose_name='Unit'),
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dose')),
                ('frequency', models.CharField(blank=True, max_length=50, null=True, verbose_name='Frequency')),
                ('duration', models.CharField(blank=True, max_length=50, null=True, verbose_name='Duration')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Total Quantity')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Instructions')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescribed_as', to='pharmacy.medicine', verbose_name='Medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.prescription', verbose_name='Prescription')),
            ],
            options={
                'verbose_name': 'Prescription Item',
                'verbose_name_plural': 'Prescription Items',
            },
        ),
        migrations.AddField(
            model_name='dispenseditem',
            name='prescription_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensed_records', to='pharmacy.prescriptionitem', verbose_name='Prescription Item'),
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Batch Number')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('quantity_received', models.PositiveIntegerField(default=0, verbose_name='Quantity Received')),
                ('quantity_remaining', models.PositiveIntegerField(default=0, verbose_name='Quantity Remaining')),
                ('source_type', models.CharField(choices=[('PURCHASE', 'Clinic Purchase (Sosa Rasik)'), ('GOV_DONATION', 'Government Donation (Doasaun Governu)'), ('NGO_INT', 'International NGO Donation (ONG Internasional)'), ('NGO_NAT', 'National NGO Donation (ONG Nasional)'), ('VOLUNTEER', 'Volunteer Donation (Voluntariu)'), ('OTHER', 'Other (Seluk)')], default='PURCHASE', max_length=20, verbose_name='Source / Origem')),
                ('donor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Donor / Organization Name')),
                ('supplier', models.CharField(blank=True, max_length=200, null=True, verbose_name='Supplier / Vendor')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, verbose_name='Received Date / Data Simu')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unit Price (USD)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_batches', to='pharmacy.medicine', verbose_name='Medicine')),
            ],
            options={
                'verbose_name': 'Stock Batch',
                'verbose_name_plural': 'Stock Batches',
                'ordering': ['expiry_date', 'purchase_date'],
            },
        ),
        migrations.AddField(
            model_name='dispenseditem',
            name='stock_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispensations', to='pharmacy.stockbatch', verbose_name='Stock Batch'),
        ),
        migrations.DeleteModel(
            name='StockEntry',
        ),
        migrations.RemoveField(
            model_name='dispenseditem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dispenseditem',
            name='dosage_instructions',
        ),
        migrations.RemoveField(
            model_name='dispenseditem',
            name='quantity',
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['expiry_date'], name='idx_batch_expiry'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=django.contrib.postgres.indexes.GinIndex(fields=['batch_number'], name='idx_batch_num_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
