# Generated by Django 5.2.12 on 2026-05-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_alter_dispenseditem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='conversion_multiplier',
            field=models.PositiveIntegerField(default=1, help_text='e.g. 10 tablets per strip', verbose_name='Conversion Multiplier'),
        ),
    ]
