# Generated by Django 5.2.12 on 2026-05-04 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_medicine_conversion_multiplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['name'], 'permissions': [('view_menu_tb_stock', 'Can see Stock Aimoruk TB in sidebar'), ('view_menu_tb_pharmacy', 'Can see Mini Farmásia TB in sidebar')], 'verbose_name': 'Medicine', 'verbose_name_plural': 'Medicines'},
        ),
    ]
