# Generated by Django 5.2.12 on 2026-05-11 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0015_alter_medicine_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['name'], 'verbose_name': 'Medicine', 'verbose_name_plural': 'Medicines'},
        ),
    ]
